{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "x-identity.secretName" . }}
  labels:
    {{- include "x-identity.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ required "secret.dbUser is required" .Values.secret.dbUser | quote }}
  DB_PASSWORD: {{ required "secret.dbPassword is required" .Values.secret.dbPassword | quote }}
  JWT_SECRET: {{ required "secret.jwtSecret is required" .Values.secret.jwtSecret | quote }}
{{- end }}
